### ISSUE TITLE
'pip' is not recognized

### ISSUE THREAD

**Issue by farzadroshanzamir** [najafiseo/OpenAI-tool#1]
این دستور رو نمیشناسه
C:\Users\xs>pip install -r requirements.txt
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by najafiseo** [comment]
دوتا مشکل ممکنه باشه یکی این ک پایتون رو نصب نکرده باشید اگه نصب کردید و این مشکل هستش ٫ مشکل از ,اتصال به pip هستش 
راحت ترین کاری که میتونید انجام بدید اینه ک پایتون رو پاک کنید و دوباره نصب کنید و موقع نصب حتما تیک add python to path رو بزنید

**Comment by farzadroshanzamir** [comment]
متشکر. دستی اد کردم https://datatofish.com/add-python-to-windows-path/
